knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 20 # In seconds
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'        
        options:
            page-size: A4
            margin-top: 10mm
            margin-right: 5mm
            margin-bottom: 10mm
            margin-left: 5mm

    image:
        enabled:    false
        #binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        #options:    []
